ENABLED = true

[SETTINGS]
url_prefix = "/"
#subdomain = ""
#url_defaults = {}
#static_folder = "static"
template_folder = "templates"
#static_url_path = "/static/www"
#root_path = ""
#cli_group = ""

[SESSION]
#www_session = "yes"

[DATABASE_BIND]
ENABLED = true
DIALECT = "sqlite"
DATABASE_NAME = "www"
LOCATION = ""
PORT = ""
USERNAME = ""
PASSWORD = ""
