ENABLED = "yes"

[SETTINGS]
URL_PREFIX = "/www_nested"
#SUBDOMAIN = ""
#URL_DEFAULTS = {}
#STATIC_FOLDER = "static"
TEMPLATE_FOLDER = "templates"
#STATIC_URL_PATH = "/static/www_nested"
#ROOT_PATH = ""
#CLI_GROUP = ""

[SESSION]
#www_nested_session = "yes"

# Set ENABLED to true to allow the blueprint
# to create a database bind, change settings accordingly.
[DATABASE_BIND]
ENABLED = true
DIALECT = "sqlite"
DATABASE_NAME = "www_nested"
LOCATION = ""
PORT = ""
USERNAME = ""
PASSWORD = ""
