[init]
enabled = true
version = 0.1

[settings]
type = "blueprint"
structure = "fl_default"
models_folder = "models"

[blueprint]
url_prefix = "/"
template_folder = "templates"
static_folder = "static"
static_url_path = "/static"

[session]
var_in_session = "this can be loaded using fl_bp.session"
