[init]
enabled = true
version = 0.1

[settings]
type = "blueprint"
structure = "fl_default"
models_folder = ""

[blueprint]
name = "exmaple_blueprint"
url_prefix = "/"
template_folder = "templates"
static_folder = "static"
static_url_path = "/exmaple_blueprint/static"

[session]
var_in_session = "this can be loaded using fl_bp.session"
permissions = ["this", "that"]
logged_in = true
not_logged_in = false
