name: Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
      - master
      - '*.x'
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: Linux, python: '3.11', os: ubuntu-latest }
          - { name: Windows, python: '3.11', os: windows-latest }
          - { name: Mac, python: '3.11', os: macos-latest }
          - { name: '3.12-dev', python: '3.12-dev', os: ubuntu-latest }
          - { name: '3.10', python: '3.10', os: ubuntu-latest }
          - { name: '3.9', python: '3.9', os: ubuntu-latest }
          - { name: '3.8', python: '3.8', os: ubuntu-latest }
          - { name: 'PyPy', python: 'pypy-3.10', os: ubuntu-latest }
          - { name: 'Development Versions', python: '3.8', os: ubuntu-latest }
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements_dev.txt
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest